Repository graphql/graphiql, pull requests merged in 2022-08, with the labels that each got.

#2623 changeset & publishing fix for LSP bugfix
  .changeset/curly-poets-pump.md
  packages/vscode-graphql-syntax/package.json
Labels: lsp-server

#2654 [language-services] Improve autocomplete suggestions when editing type system definitions
  .changeset/chatty-timers-heal.md
  .changeset/smart-cats-marry.md
  .eslintrc.js
  .vscode/launch.json
  examples/monaco-graphql-webpack/babel.config.js
  examples/monaco-graphql-webpack/src/editors.ts
  examples/monaco-graphql-webpack/src/index.html.ejs
  examples/monaco-graphql-webpack/src/index.ts
  examples/monaco-graphql-webpack/src/schema.ts
  examples/monaco-graphql-webpack/src/style.css
  packages/codemirror-graphql/src/__tests__/hint-test.ts
  packages/graphiql-toolkit/src/create-fetcher/lib.ts
  packages/graphql-language-service-server/src/GraphQLLanguageService.ts
  packages/graphql-language-service/src/interface/__tests__/__schema__/StarWarsSchema.graphql
  packages/graphql-language-service/src/interface/__tests__/getAutocompleteSuggestions-test.ts
  packages/graphql-language-service/src/interface/getAutocompleteSuggestions.ts
  packages/graphql-language-service/src/parser/Rules.ts
  packages/graphql-language-service/src/parser/types.ts
  packages/monaco-graphql/src/LanguageService.ts
  packages/monaco-graphql/src/languageFeatures.ts
Labels: enhancement, language-interface, monaco-graphql

#2711 Version Packages
  .changeset/eight-wombats-refuse.md
  .changeset/healthy-cougars-sell.md
  .changeset/sweet-tomatoes-protect.md
  examples/graphiql-explorer/package.json
  examples/graphiql-webpack/package.json
  packages/graphiql-react/CHANGELOG.md
  packages/graphiql-react/package.json
  packages/graphiql/CHANGELOG.md
  packages/graphiql/package.json
Labels: do not merge
